org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

maven_group=com.one_studios
mod_id=locator_lodestones

mod_version=1.5.3
mod_subversion=A

min_supported_version=26.3
max_supported_version=26.3

minecraft_version=26.3
loader_version=0.19.5
fabric_version=0.162.0+26.3
core_version=1.3.1+26.3+A
modmenu_version=21.0.0
